import mongoose from "mongoose";

const bookingSchema=new mongoose.Schema({
    userId:{
       type:mongoose.Schema.Types.ObjectId,ref:"users"
    },
    flightId:{
        type:mongoose.Schema.Types.ObjectId,ref:"flights"
    },
    bookingReference:{
      type:String,
      unique:true,
      required:true
    },
    cancellationReason:{
       type:String
    },
    refundAmount:{
      type:Number,
      default:0
    },
    passengers:[
        {
          name:{
            type:String,
            required:true
          },
          age:{
            type:Number,
            required:true
          },
          gender:{
            type:String,
            enum:["Male","Female","Other"],
            required:true
          },
          passportNumber:{
            type:String,
            required:true
          }
        }
    ],
    seatNumbers:{
        type:[String],
        required:true
    },
    status:{
    type:String,
    enum:[
        "Pending",
        "Confirmed",
        "Cancelled",
        "Completed"
    ],
    default:"Pending"
    },
    paymentStatus:{
    type:String,
    enum:[
        "Pending",
        "Paid",
        "Refunded"
    ],
    default:"Pending"
   },
   totalAmount:{
    type:Number,
    required:true
   }
},{strict:true,timestamps:true})

export const bookingModel=mongoose.model("booking",bookingSchema);